#!/bin/bash

set -e

MYDIR="`dirname "$BASH_SOURCE"`"
if [ -f "$MYDIR/paths.inc" ]; then
	source "$MYDIR/paths.inc"
else
	MYDIRABS="`readlink -f "$MYDIR"`"
	METALLOC_PATH="$MYDIRABS/../gperftools-metalloc"
	TCMALLOC_PATH="$MYDIRABS/../gperftools"
	CUSTOMLIBC_PATH="$MYDIRABS/../glibc-build"
	DEFAULTLIBPATHS=/usr/lib/x86_64-linux-gnu/:/lib/x86_64-linux-gnu/:/usr/lib
fi

SAFESTACK_OPTIONS=metalloc=true:largestack=true METALLOC_DEEPMETADATA=true LD_PRELOAD=$METALLOC_PATH/.libs/libtcmalloc.so $CUSTOMLIBC_PATH/elf/ld-linux-x86-64.so.2 --library-path $CUSTOMLIBC_PATH:$CUSTOMLIBC_PATH/math:$CUSTOMLIBC_PATH/elf:$CUSTOMLIBC_PATH/dlfcn:$CUSTOMLIBC_PATH/nss:$CUSTOMLIBC_PATH/nis:$CUSTOMLIBC_PATH/rt:$CUSTOMLIBC_PATH/resolv:$CUSTOMLIBC_PATH/crypt:$CUSTOMLIBC_PATH/nptl:$DEFAULTLIBPATHS "$@"

#LD_PRELOAD=TCMALLOC_PATH/.libs/libtcmalloc.so "$@"
